[package]
name = "aoc2-sol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []

[dependencies]
anyhow = { workspace = true }
bitvec = "1.0.1"
console = { workspace = true }
getset = { workspace = true }
indexmap = { workspace = true }
itertools = "0.13.0"
lazy_static = { workspace = true }
md-5 = "0.10.6"
ndarray = "0.16.0"
pathfinding = "4.10.0"
petgraph = "0.6.5"
rayon = "1.10.0"
regex = { workspace = true }
serde_json = "1.0.122"

[build-dependencies]
rustversion = { workspace = true }
