[package]
name = "aoc2-sol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bitvec = "1.0.1"
console = "0.15.5"
getset = "0.1.2"
indexmap = "1.9.2"
itertools = "0.10.5"
lazy_static = "1.4.0"
md-5 = "0.10.5"
ndarray = "0.15.6"
pathfinding = "4.2.1"
petgraph = "0.6.3"
rayon = "1.6.1"
regex = "1.7.1"
serde_json = "1.0.92"
