[workspace]
resolver = "2"

members = [
  "aoc2-bin",
  "aoc2-sol",
]

[workspace.dependencies]
anyhow = "1.0.86"
console = "0.15.8"
getset = "0.1.2"
indexmap = "2.3.0"
lazy_static = "1.5.0"
regex = "1.10.6"
rustversion = "1.0.17"