[workspace]
resolver = "2"

members = ["aoc2-bin", "aoc2-ft", "aoc2-sol"]

[workspace.dependencies]
anyhow = "1.0.94"
console = "0.15.8"
getset = "0.1.3"
indexmap = "2.7.0"
lazy_static = "1.5.0"
regex = "1.11.1"
rustversion = "1.0.18"
