[package]
name = "aoc2-ft"
version = "0.1.0"
edition = "2024"

[features]
unstable = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
getset.workspace = true
tera = "1.20.0"

[build-dependencies]
rustversion.workspace = true
