[package]
name = "aoc2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []

[dependencies]
anyhow = "1.0.69"
aoc2-sol = { path = "../aoc2-sol" }
clap = {version = "4.1.4", features = ["derive"] }
console = "0.15.5"
getset = "0.1.2"
indexmap = "2.2.6"
lazy_static = "1.4.0"
rand = "0.8.5"

[build-dependencies]
anyhow = "1.0.69"
rustversion = "1.0.11"
vergen-gix = { version = "1.0.0-beta.2", features = [
  "build",
  "cargo",
  "rustc",
  "si",
] }

[dev-dependencies]
regex = "1.7.1"
