[package]
name = "aoc2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
aoc2-sol = { path = "../aoc2-sol" }
clap = {version = "4.0.26", features = ["derive"] }
console = "0.15.2"
getset = "0.1.2"
indexmap = "1.7.0"
lazy_static = "1.4.0"
rand = "0.8.4"

[build-dependencies]
anyhow = "1.0.42"
rustversion = "1.0.5"
vergen = "7.3.1"

[dev-dependencies]
regex = "1.5.4"
