[package]
name = "aoc2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []

[dependencies]
anyhow = { workspace = true }
aoc2-sol = { path = "../aoc2-sol" }
clap = {version = "4.5.20", features = ["derive"] }
console = { workspace = true }
getset = { workspace = true }
indexmap = { workspace = true }
lazy_static = { workspace = true }
rand = "0.8.5"

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { version = "1.0.2", features = [
  "build",
  "cargo",
  "rustc",
  "si",
] }

[dev-dependencies]
regex = { workspace = true }
